"""Turn the Legacy LLM card texts of one issue into a V2 card-review file.

The Legacy database keeps card texts only for the current day: the docx backfill deletes
and recreates `materials` every morning and `material_llm_summaries` cascades with it.
So texts regenerated by `pipeline/scripts/agpm_radar_openclaw_analysis.py` for an earlier
issue reach V2 only through a correction published the same day. This tool writes the
review that `publish_v2_card_review.py` takes: one card per material that carries a
text of the requested prompt version and is part of the V2 issue. The other cards of the
issue are left untouched by the correction.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from collections import Counter
from pathlib import Path
from typing import cast

from packages.contracts.json_types import JsonValue
from packages.domain.snapshot import JsonObject, canonical_json_line
from packages.legacy_bridge.importer import deterministic_id
from packages.storage.content_pointer import read_content_pointer
from packages.storage.safe_files import atomic_write_new


def export_review(
    *,
    legacy_db: Path,
    v2_db: Path,
    issue_date: str,
    prompt_version: str,
) -> tuple[JsonObject, dict[str, int]]:
    with sqlite3.connect(f"file:{v2_db}?mode=ro", uri=True) as v2:
        issue = v2.execute(
            "SELECT issue_id FROM issues WHERE issue_date = ?", (issue_date,)
        ).fetchone()
        if issue is None:
            raise ValueError(f"V2 issue is absent: {issue_date}")
        v2_ids = {
            str(row[0])
            for row in v2.execute(
                "SELECT material_id FROM issue_materials WHERE issue_id = ?", (str(issue[0]),)
            )
        }
    with sqlite3.connect(f"file:{legacy_db}?mode=ro", uri=True) as legacy:
        rows = legacy.execute(
            """
            SELECT material_id, short_text, agpm_angle, model, status, prompt_version
            FROM material_llm_summaries WHERE issue_date = ? ORDER BY material_id
            """,
            (issue_date,),
        ).fetchall()
    cards: list[JsonObject] = []
    stats: Counter[str] = Counter()
    for material_id, short_text, agpm_angle, model, status, version in rows:
        v2_id = deterministic_id("material", str(material_id))
        if v2_id not in v2_ids:
            stats["not_in_v2_issue"] += 1
            continue
        if status != "success" or version != prompt_version:
            stats["without_new_text"] += 1
            continue
        cards.append(
            {
                "agpmAngle": str(agpm_angle),
                "materialId": v2_id,
                "model": str(model),
                "shortText": str(short_text),
            }
        )
    if not cards:
        raise ValueError(f"no card of {issue_date} carries a {prompt_version} text")
    stats["exported"] = len(cards)
    stats["v2_untouched"] = len(v2_ids) - len(cards)
    models = Counter(str(card["model"]) for card in cards)
    review: JsonObject = {
        "cards": cast(list[JsonValue], cards),
        "issueDate": issue_date,
        "model": models.most_common(1)[0][0],
        "promptVersion": prompt_version,
        "status": "success",
    }
    return review, dict(stats)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--legacy-db", required=True, type=Path)
    parser.add_argument("--source-root", required=True, type=Path)
    parser.add_argument("--issue-date", required=True)
    parser.add_argument("--prompt-version", default="openclaw-card-summary-ru-v4")
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    pointer = read_content_pointer(args.source_root)
    review, stats = export_review(
        legacy_db=args.legacy_db,
        v2_db=pointer.database_path,
        issue_date=args.issue_date,
        prompt_version=args.prompt_version,
    )
    atomic_write_new(args.output, canonical_json_line(review), mode=0o600)
    print(json.dumps({"issueDate": args.issue_date, **stats}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
