// Real Chromium interaction against deterministic HTTP responses. Run after
// scripts/verify.sh; uses the repository's existing QA Playwright installation.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const { chromium } = await import(process.env.RADAR_PLAYWRIGHT_MODULE || '../../work/qa/node_modules/playwright/index.mjs');
const web = new URL('../apps/web/', import.meta.url);
const catalog = JSON.parse(execFileSync(fileURLToPath(new URL('../.venv/bin/python', import.meta.url)), ['-c', 'import json; from packages.contracts.rubrics import rubric_catalog; print(json.dumps(rubric_catalog()))'], { cwd: new URL('../', import.meta.url) }));
const labels = Object.fromEntries(catalog.map(row => [row.id, row.label]));
const W = 'workflow_orchestration', S = 'security_access', F = 'funding_ma';
const card = (id, title, perimeter, rubrics) => ({ id, title, perimeter, rubrics, issueDate: '2026-09-09', url: `https://example.test/${id}`, brief: 'Проверка фильтрации', agpmTakeaway: 'Проверить результат', verdict: 'core', llm: { status: 'fallback' } });
const cards = [card('a', 'Alpha', 'near', [W, 'agpm_pmo_portfolio']), card('b', 'Beta', 'mid', [S]), card('c', 'Gamma', 'near', [W, S]), card('d', 'Delta', 'far', [F])];
const periodCards = [...Array.from({ length: 104 }, (_, i) => card(`p${i}`, `Period ${i}`, 'near', [W])), card('last', 'Last page', 'far', [S])];
const counts = rows => ({ included: rows.length, viewed: rows.length + 10, cut: 10, near: rows.filter(r => r.perimeter === 'near').length, mid: rows.filter(r => r.perimeter === 'mid').length, far: rows.filter(r => r.perimeter === 'far').length, core: rows.length, adjacent: 0 });
const issue = { issueDate: '2026-09-09', issueNumber: 95, materials: cards, stats: counts(cards), theses: [] };
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = [], requests = [];
  let holdPeriod = null, failCatalog = false, hangCatalog = false;
  await context.route('https://radar.test/**', async route => {
    const u = new URL(route.request().url());
    requests.push(u.pathname + u.search);
    if (u.pathname.startsWith('/api/')) {
      let payload = {};
      if (u.pathname === '/api/rubric-catalog') {
        if (hangCatalog) return; // Browser must abort this optional request.
        if (failCatalog) return route.fulfill({ status: 503, json: {} });
        payload = catalog;
      } else if (u.pathname === '/api/latest' || u.pathname.startsWith('/api/issues/')) payload = { ...issue, issueDate: u.pathname.startsWith('/api/issues/') ? u.pathname.split('/').at(-1) : issue.issueDate };
      else if (u.pathname === '/api/rubrics') payload = catalog.filter(row => cards.some(card => card.rubrics.includes(row.id))).map(row => ({ id: row.id, title: row.title, label: row.label, count: cards.filter(card => card.rubrics.includes(row.id)).length }));
      else if (u.pathname === '/api/materials' || u.pathname === '/api/search') {
        if (holdPeriod) await holdPeriod;
        let rows = periodCards;
        const perimeter = u.searchParams.get('perimeter');
        if (perimeter && perimeter !== 'all') rows = rows.filter(row => row.perimeter === perimeter);
        const q = (u.searchParams.get('q') || '').toLowerCase().split(/\s+/).filter(Boolean);
        rows = rows.filter(row => q.every(word => [row.title, row.brief, row.agpmTakeaway, ...row.rubrics.map(id => labels[id])].join(' ').toLowerCase().includes(word)));
        const offset = Number(u.searchParams.get('cursor') || 0);
        payload = { items: rows.slice(offset, offset + 100), nextCursor: offset + 100 < rows.length ? String(offset + 100) : null };
      } else if (u.pathname === '/api/stats') payload = counts(periodCards);
      else if (u.pathname === '/api/timeseries') payload = { items: [{ date: issue.issueDate, ...issue.stats }] };
      else if (u.pathname === '/api/sources') payload = [{ name: u.searchParams.get('date') ? `Issue ${u.searchParams.get('date')}` : `Sources ${u.searchParams.get('period')}`, included: u.searchParams.get('date') ? 4 : 105 }];
      else if (u.pathname === '/api/issues') payload = { items: [] };
      return route.fulfill({ json: payload });
    }
    const relative = u.pathname.startsWith('/assets/') ? u.pathname.slice(8) : 'index.html';
    const contentType = relative.endsWith('.mjs') ? 'text/javascript' : relative.endsWith('.css') ? 'text/css' : relative.endsWith('.ttf') ? 'font/ttf' : 'text/html';
    return route.fulfill({ body: await fs.readFile(new URL(relative, web)), contentType });
  });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(String(error)));
  const ready = async () => { await page.waitForFunction(() => document.querySelectorAll('#columns .card').length > 0 && !document.querySelector('#columns').classList.contains('loading')); };
  const cardCount = async n => { await page.waitForFunction(n => document.querySelectorAll('#columns .card').length === n && !document.querySelector('#columns').classList.contains('loading'), n); };
  const tag = id => page.locator(`#columns [data-rubric="${id}"]`).first();
  const rubric = id => page.locator(`#rubricator [data-rubric="${id}"]`);
  await page.goto('https://radar.test/'); await ready();
  await cardCount(4);
  await page.waitForFunction(() => document.querySelector('#footerSources').textContent.includes('Issue 2026-09-09'));
  assert.match(await page.locator('#footerSourcesLabel').innerText(), /9 сен/i);
  assert.ok(!requests.includes('/api/sources?period=30d'), 'latest issue must not load 30-day sources');
  assert.equal(await page.locator('#rubricator [data-rubric]').count(), 11, 'zero-count rubrics remain available');
  assert.equal(await rubric(W).locator('strong').innerText(), 'Оркестрация');
  const before = requests.filter(p => p.startsWith('/api/')).length;
  await tag(W).focus(); await page.keyboard.press('Enter'); await cardCount(2);
  assert.equal(await tag(W).getAttribute('aria-pressed'), 'true');
  assert.equal(await rubric(W).getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator(`#rubrics [data-rubric-bar="${W}"]`).getAttribute('aria-pressed'), 'true');
  assert.equal(await page.evaluate(() => document.activeElement.dataset.rubric), W);
  await tag(S).click(); await cardCount(3);
  assert.equal(requests.filter(p => p.startsWith('/api/')).length, before, 'rubric clicks make no API requests');
  await page.goBack(); await cardCount(2);
  assert.ok(!new URL(page.url()).searchParams.get('rubrics').includes(S));
  await page.goForward(); await cardCount(3);
  await page.reload(); await cardCount(3);
  await page.locator(`#activeFilter [data-rubric="${W}"]`).click(); await cardCount(2);
  assert.equal(await rubric(W).getAttribute('aria-pressed'), 'false');
  await page.locator('#activeFilter [data-clear-filter="rubrics"]').click(); await cardCount(4);
  await rubric(F).click(); await cardCount(1);
  assert.equal(await page.evaluate(() => document.activeElement.id), 'filterResults');
  await page.locator('#resetFilters').click(); await cardCount(4);
  await page.locator('#search').fill('Alpha'); await cardCount(1);
  await rubric(F).click(); await cardCount(0);
  assert.equal(await page.locator('#filterEmpty').isVisible(), true);
  await page.locator('#filterEmpty [data-clear-filter="rubrics"]').click(); await cardCount(1);
  assert.equal(await page.locator('#search').inputValue(), 'Alpha');
  await page.locator('#resetFilters').click(); await cardCount(4);
  await page.locator('[data-period="30d"]').click(); await cardCount(105);
  assert.ok(requests.some(p => p.includes('cursor=100')), 'all period pages fetched');
  await page.waitForFunction(() => document.querySelector('#footerSources').textContent.includes('Sources 30d'));
  assert.equal(await page.locator('#footerSourcesLabel').innerText(), 'ИСТОЧНИКИ ЗА 30 ДНЕЙ');
  await rubric(S).click(); await cardCount(1);
  assert.match(await page.locator('#columns').innerText(), /Last page/);
  const url = page.url(); await page.reload(); await cardCount(1); assert.equal(page.url(), url);
  await page.locator('#activeFilter [data-clear-filter="rubrics"]').click(); await cardCount(105);
  await page.locator('#search').fill('Period'); await cardCount(104);
  await page.locator('[data-perimeter="near"]').click(); await cardCount(104);
  await rubric(S).click(); await cardCount(0);
  assert.match(page.url(), /period=30d/); assert.match(page.url(), /perimeter=near/); assert.match(page.url(), /q=Period/);
  await page.reload(); await cardCount(0);
  await page.locator('#activeFilter [data-clear-filter="rubrics"]').click(); await cardCount(104);
  await page.goto('https://radar.test/?period=invalid&perimeter=invalid&rubrics=unknown,%3Cscript%3E'); await cardCount(4);
  assert.equal(page.url(), 'https://radar.test/');
  await page.goto('https://radar.test/issues/2026-09-08?rubrics=workflow_orchestration'); await cardCount(2);
  assert.match(page.url(), /issues\/2026-09-08/);
  await page.waitForFunction(() => document.querySelector('#footerSources').textContent.includes('Issue 2026-09-08'));
  assert.match(await page.locator('#footerSourcesLabel').innerText(), /8 сен/i);
  await page.goto('https://radar.test/issues/2026-09-07?period=yesterday&rubrics=workflow_orchestration'); await cardCount(2);
  assert.ok(!page.url().includes('period=yesterday'));
  assert.equal(await page.locator('[data-period="issue"]').getAttribute('class'), 'segment is-active');
  await page.goto('https://radar.test/'); await cardCount(4);
  let release;
  holdPeriod = new Promise(resolve => { release = resolve; });
  await page.locator('[data-period="7d"]').click();
  await rubric(S).click();
  holdPeriod = null; release(); await cardCount(1);
  assert.equal(await page.evaluate(() => document.activeElement.id), 'filterResults');
  assert.match(await page.locator('#columns').innerText(), /Last page/);
  assert.deepEqual(errors, []);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('https://radar.test/'); await cardCount(4);
  assert.ok((await tag(W).boundingBox()).height >= 40);
  await tag(W).click(); await cardCount(2);
  await page.screenshot({ path: '/tmp/radar-rubric-mobile-before.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({ path: '/tmp/radar-rubric-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: '/tmp/radar-rubric-desktop.png', fullPage: true });
  failCatalog = true;
  await page.goto('https://radar.test/'); await cardCount(4);
  await tag(W).click(); await cardCount(2);
  await page.locator('#search').fill('Оркестрация'); await cardCount(2);
  await page.locator('[data-period="7d"]').click(); await cardCount(104);
  hangCatalog = true;
  const started = Date.now();
  await page.goto('https://radar.test/'); await cardCount(4);
  assert.ok(Date.now() - started < 4500, 'hung optional catalogue cannot block the issue');
  assert.deepEqual(errors, []);
  console.log('Rubric browser smoke: PASS (toggle/OR, synchronized controls, zero counts, no reload, focus, URL/history, search/perimeter, pagination, pending load, fallback, mobile)');
} finally { await browser.close(); }
